name: EpicGear
main: me.frodenkvist.armoreditor.ArmorEditor
version: 1.0.9
depend: [PVPBalance]
softdepend: [EpicBoss, Towny, Vault]
description: >
             Test. port plugin.
commands:
    ae:
        description: Starter command.
